export const ROUTES = [
  { prettyName: 'Request', name: 'request', icon: 'ExternalLink' },
  { prettyName: 'Cookies', name: 'cookies', icon: 'Cookie' },
  { prettyName: 'Env Vars', name: 'environment', icon: 'Brackets' },
  // { prettyName: 'Servers', name: 'servers', icon: 'Server' },
  // { label: 'Git Sync', icon: 'Branch', path: '/git-sync' },
] as const

export const ICONS = [
  'basic-shape-diamond',
  'basic-shape-hexagon',
  'basic-shape-primary-circle-ellipse-round',
  'basic-shape-primary-square-rectangle',
  'basic-shape-shield',
  'computer-device-desktop-monitor',
  'computer-device-desktop',
  'computer-device-laptop',
  'computer-device-mobile-phone-android-samsung-back',
  'computer-device-mobile-phone-android-samsung',
  'computer-device-mobile-phone-iphone-x-back',
  'computer-device-mobile-phone-iphone-x',
  'computer-device-mobile-tablet-touch',
  'computer-device-mobile-tablet',
  'computer-device-network-ethernet-cat6',
  'computer-device-network-lan-www',
  'computer-device-network-wifi-connection',
  'computer-device-network-wifi-router',
  'ecology-science-erlenmeyer-flask',
  'image-flash-lightning',
  'image-picture-flower',
  'interface-alert-exclamation-diamond',
  'interface-alert-exclamation-triangle-warning',
  'interface-alert-information-circle',
  'interface-award-crown',
  'interface-bookmark-tag',
  'interface-bookmark',
  'interface-calendar-date-one',
  'interface-content-book-open-pages',
  'interface-content-book-page',
  'interface-content-file',
  'interface-content-folder',
  'interface-copy-clipboard',
  'interface-edit-attachment',
  'interface-edit-binocular',
  'interface-edit-magic-wand',
  'interface-edit-tool-paint-roller',
  'interface-edit-tool-pencil',
  'interface-favorite-award',
  'interface-favorite-flag',
  'interface-favorite-heart',
  'interface-favorite-star',
  'interface-favorite-stars-sparkles',
  'interface-hierarchy-flowchart',
  'interface-home-house',
  'interface-hyperlink',
  'interface-lighting-brightness',
  'interface-lock-closed',
  'interface-lock-open-unlock',
  'interface-login-key',
  'interface-search',
  'interface-setting-cog',
  'interface-share-megaphone-bullhorn',
  'interface-share-rocket',
  'interface-share-satellite',
  'interface-share-space-ship',
  'interface-share',
  'interface-signal-square',
  'interface-time-clock-circle',
  'interface-time-hour-glass',
  'interface-users-multiple',
  'interface-weather-moon',
  'mail-chat-bubble-square',
  'mail-send-email-paper-airplane',
  'mail-send-envelope',
  'money-cashier-receipt',
  'money-currency-dollar-pay',
  'money-graph-arrow-increase',
  'money-graph-bar-chart-increase',
  'nature-ecology-leaf',
  'phone-telephone',
  'programming-bug',
  'programming-cloud',
  'programming-computer-database-server',
  'programming-computer-database',
  'programming-module-four-layout',
  'programming-module-three',
  'programming-module',
  'programming-script-code',
  'shopping-cart',
  'shopping-gift-present',
  'shopping-shipping-box-parcel-package',
  'tag-new-circle',
  'travel-map-earth-globe',
]
